/*
 * Port_cfg.h
 *
 *  Created on: Jan 17, 2021
 *      Author: hossam
 */

#ifndef PORT_CFG_H_
#define PORT_CFG_H_

#define PORT_u8OUTPUT_HIGH		1
#define PORT_u8OUTPUT_LOW		2
#define PORT_u8INPUT_HIGH_IMP	3
#define PORT_u8INPUT_PULL_UP	4
/**/
#define PORT_u8PIN_0_INIT_MODE		   PORT_u8OUTPUT_LOW
#define PORT_u8PIN_1_INIT_MODE         PORT_u8OUTPUT_LOW
#define PORT_u8PIN_2_INIT_MODE         PORT_u8OUTPUT_LOW
#define PORT_u8PIN_3_INIT_MODE         PORT_u8OUTPUT_LOW
#define PORT_u8PIN_4_INIT_MODE         PORT_u8OUTPUT_LOW
#define PORT_u8PIN_5_INIT_MODE         PORT_u8OUTPUT_LOW
#define PORT_u8PIN_6_INIT_MODE         PORT_u8OUTPUT_LOW
#define PORT_u8PIN_7_INIT_MODE         PORT_u8OUTPUT_LOW
#define PORT_u8PIN_8_INIT_MODE         PORT_u8OUTPUT_LOW
#define PORT_u8PIN_9_INIT_MODE         PORT_u8OUTPUT_LOW
#define PORT_u8PIN_10_INIT_MODE        PORT_u8OUTPUT_LOW
#define PORT_u8PIN_11_INIT_MODE        PORT_u8OUTPUT_LOW
#define PORT_u8PIN_12_INIT_MODE        PORT_u8OUTPUT_LOW
#define PORT_u8PIN_13_INIT_MODE        PORT_u8OUTPUT_LOW
#define PORT_u8PIN_14_INIT_MODE        PORT_u8OUTPUT_LOW
#define PORT_u8PIN_15_INIT_MODE        PORT_u8OUTPUT_LOW
#define PORT_u8PIN_16_INIT_MODE        PORT_u8OUTPUT_LOW
#define PORT_u8PIN_17_INIT_MODE        PORT_u8OUTPUT_LOW
#define PORT_u8PIN_18_INIT_MODE        PORT_u8OUTPUT_LOW
#define PORT_u8PIN_19_INIT_MODE        PORT_u8OUTPUT_LOW
#define PORT_u8PIN_20_INIT_MODE        PORT_u8INPUT_PULL_UP
#define PORT_u8PIN_21_INIT_MODE        PORT_u8INPUT_PULL_UP
#define PORT_u8PIN_22_INIT_MODE        PORT_u8INPUT_PULL_UP
#define PORT_u8PIN_23_INIT_MODE        PORT_u8INPUT_PULL_UP
#define PORT_u8PIN_24_INIT_MODE        PORT_u8OUTPUT_LOW
#define PORT_u8PIN_25_INIT_MODE        PORT_u8OUTPUT_LOW
#define PORT_u8PIN_26_INIT_MODE        PORT_u8OUTPUT_LOW
#define PORT_u8PIN_27_INIT_MODE        PORT_u8OUTPUT_LOW
#define PORT_u8PIN_28_INIT_MODE        PORT_u8OUTPUT_LOW
#define PORT_u8PIN_29_INIT_MODE        PORT_u8OUTPUT_LOW
#define PORT_u8PIN_30_INIT_MODE        PORT_u8OUTPUT_LOW
#define PORT_u8PIN_31_INIT_MODE        PORT_u8OUTPUT_LOW

#endif /* PORT_CFG_H_ */
