/*
 * Port_priv.h
 *
 *  Created on: Jan 17, 2021
 *      Author: hossam
 */

#ifndef PORT_PRIV_H_
#define PORT_PRIV_H_

#define PORT_u8LOW	0
#define PORT_u8High	1

#define PORT_u8OUTPUT	1
#define PORT_u8INPUT	0

#define PORT_u8PIN_0_DEFAULT_VALUE		PORT_u8LOW
#define PORT_u8PIN_1_DEFAULT_VALUE		PORT_u8LOW
#define PORT_u8PIN_2_DEFAULT_VALUE      PORT_u8LOW
#define PORT_u8PIN_3_DEFAULT_VALUE      PORT_u8LOW
#define PORT_u8PIN_4_DEFAULT_VALUE      PORT_u8LOW
#define PORT_u8PIN_5_DEFAULT_VALUE      PORT_u8LOW
#define PORT_u8PIN_6_DEFAULT_VALUE      PORT_u8LOW
#define PORT_u8PIN_7_DEFAULT_VALUE      PORT_u8LOW
#define PORT_u8PIN_8_DEFAULT_VALUE      PORT_u8LOW
#define PORT_u8PIN_9_DEFAULT_VALUE      PORT_u8LOW
#define PORT_u8PIN_10_DEFAULT_VALUE     PORT_u8LOW
#define PORT_u8PIN_11_DEFAULT_VALUE     PORT_u8LOW
#define PORT_u8PIN_12_DEFAULT_VALUE     PORT_u8LOW
#define PORT_u8PIN_13_DEFAULT_VALUE     PORT_u8LOW
#define PORT_u8PIN_14_DEFAULT_VALUE     PORT_u8LOW
#define PORT_u8PIN_15_DEFAULT_VALUE     PORT_u8LOW
#define PORT_u8PIN_16_DEFAULT_VALUE     PORT_u8LOW
#define PORT_u8PIN_17_DEFAULT_VALUE     PORT_u8LOW
#define PORT_u8PIN_18_DEFAULT_VALUE     PORT_u8LOW
#define PORT_u8PIN_19_DEFAULT_VALUE     PORT_u8LOW
#define PORT_u8PIN_20_DEFAULT_VALUE     PORT_u8LOW
#define PORT_u8PIN_21_DEFAULT_VALUE     PORT_u8LOW
#define PORT_u8PIN_22_DEFAULT_VALUE     PORT_u8LOW
#define PORT_u8PIN_23_DEFAULT_VALUE     PORT_u8LOW
#define PORT_u8PIN_24_DEFAULT_VALUE     PORT_u8LOW
#define PORT_u8PIN_25_DEFAULT_VALUE     PORT_u8LOW
#define PORT_u8PIN_26_DEFAULT_VALUE     PORT_u8LOW
#define PORT_u8PIN_27_DEFAULT_VALUE     PORT_u8LOW
#define PORT_u8PIN_28_DEFAULT_VALUE     PORT_u8LOW
#define PORT_u8PIN_29_DEFAULT_VALUE     PORT_u8LOW
#define PORT_u8PIN_30_DEFAULT_VALUE     PORT_u8LOW
#define PORT_u8PIN_31_DEFAULT_VALUE     PORT_u8LOW


#define PORT_u8PIN_0_DEFAULT_DIR		PORT_u8OUTPUT
#define PORT_u8PIN_1_DEFAULT_DIR		PORT_u8OUTPUT
#define PORT_u8PIN_2_DEFAULT_DIR        PORT_u8OUTPUT
#define PORT_u8PIN_3_DEFAULT_DIR        PORT_u8OUTPUT
#define PORT_u8PIN_4_DEFAULT_DIR        PORT_u8OUTPUT
#define PORT_u8PIN_5_DEFAULT_DIR        PORT_u8OUTPUT
#define PORT_u8PIN_6_DEFAULT_DIR        PORT_u8OUTPUT
#define PORT_u8PIN_7_DEFAULT_DIR        PORT_u8OUTPUT
#define PORT_u8PIN_8_DEFAULT_DIR        PORT_u8OUTPUT
#define PORT_u8PIN_9_DEFAULT_DIR        PORT_u8OUTPUT
#define PORT_u8PIN_10_DEFAULT_DIR       PORT_u8OUTPUT
#define PORT_u8PIN_11_DEFAULT_DIR       PORT_u8OUTPUT
#define PORT_u8PIN_12_DEFAULT_DIR       PORT_u8OUTPUT
#define PORT_u8PIN_13_DEFAULT_DIR       PORT_u8OUTPUT
#define PORT_u8PIN_14_DEFAULT_DIR       PORT_u8OUTPUT
#define PORT_u8PIN_15_DEFAULT_DIR       PORT_u8OUTPUT
#define PORT_u8PIN_16_DEFAULT_DIR       PORT_u8OUTPUT
#define PORT_u8PIN_17_DEFAULT_DIR       PORT_u8OUTPUT
#define PORT_u8PIN_18_DEFAULT_DIR       PORT_u8OUTPUT
#define PORT_u8PIN_19_DEFAULT_DIR       PORT_u8OUTPUT
#define PORT_u8PIN_20_DEFAULT_DIR       PORT_u8OUTPUT
#define PORT_u8PIN_21_DEFAULT_DIR       PORT_u8OUTPUT
#define PORT_u8PIN_22_DEFAULT_DIR       PORT_u8OUTPUT
#define PORT_u8PIN_23_DEFAULT_DIR       PORT_u8OUTPUT
#define PORT_u8PIN_24_DEFAULT_DIR       PORT_u8OUTPUT
#define PORT_u8PIN_25_DEFAULT_DIR       PORT_u8OUTPUT
#define PORT_u8PIN_26_DEFAULT_DIR       PORT_u8OUTPUT
#define PORT_u8PIN_27_DEFAULT_DIR       PORT_u8OUTPUT
#define PORT_u8PIN_28_DEFAULT_DIR       PORT_u8OUTPUT
#define PORT_u8PIN_29_DEFAULT_DIR       PORT_u8OUTPUT
#define PORT_u8PIN_30_DEFAULT_DIR       PORT_u8OUTPUT
#define PORT_u8PIN_31_DEFAULT_DIR       PORT_u8OUTPUT


#endif /* PORT_PRIV_H_ */
